version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sns,sqs,lambda,iam
      - DEBUG=1
    volumes:
      - ./:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash -c "docker-entrypoint.sh & /docker-entrypoint-initaws.d/setup.sh && tail -f /dev/null"
    networks:
      - localstack-network

  lambda:
    build: .
    container_name: lambda
    environment:
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:transcription-topic
    volumes:
      - ./:/var/task/
    depends_on:
      - localstack
    command: ["lambda_function.lambda_handler"]
    networks:
      - localstack-network

networks:
  localstack-network:
    external: true

